# Generated by Django 3.2.13 on 2022-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tape',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
    ]
