# Generated by Django 3.2.13 on 2022-05-21 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tape', '0007_auto_20220521_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
