# Generated by Django 3.2.13 on 2022-05-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0008_entry_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
