# Generated by Django 3.2.13 on 2022-05-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0010_auto_20220521_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='tape',
            name='background',
            field=models.ImageField(blank=True, upload_to='tape-backgrounds/'),
        ),
        migrations.AddField(
            model_name='tape',
            name='picture',
            field=models.ImageField(blank=True, upload_to='tape-pictures/'),
        ),
        migrations.AlterField(
            model_name='tape',
            name='slug',
            field=models.SlugField(max_length=32, verbose_name='Ссылка'),
        ),
    ]
