# Generated by Django 3.2.13 on 2022-05-27 11:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0011_auto_20220527_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
