# Generated by Django 3.2.13 on 2022-05-28 12:58

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0012_alter_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
