# Generated by Django 3.2.13 on 2022-05-28 13:25

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0013_alter_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
