# Generated by Django 3.2.13 on 2022-05-28 13:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0014_alter_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
