# Generated by Django 3.2.13 on 2022-05-28 13:42

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0015_alter_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
