# Generated by Django 3.2.13 on 2022-05-30 14:56

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0018_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tape',
            name='description',
            field=django_quill.fields.QuillField(blank=True, max_length=400, null=True, verbose_name='Описание'),
        ),
    ]
