# Generated by Django 3.2.13 on 2022-05-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0020_alter_entry_tape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='tape.tape', verbose_name='Лента'),
        ),
    ]
