# Generated by Django 3.2.13 on 2022-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0023_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
