# Generated by Django 3.2.15 on 2022-08-23 22:01

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('username', models.SlugField(max_length=24, unique=True, verbose_name='Имя пользователя')),
                ('username_lower', models.SlugField(max_length=24, unique=True, verbose_name='Уникальное имя')),
                ('about', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Краткое описание')),
                ('full_name', models.CharField(blank=True, max_length=48, null=True, verbose_name='Полное имя')),
                ('show_full_name', models.BooleanField(default=True, verbose_name='Отображать полное имя')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администрация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Аккаунт подтвержден')),
                ('is_newbie', models.BooleanField(default=True, verbose_name='Только что зарегистрирован')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('avatar', models.ImageField(blank=True, upload_to='user-avatars/', verbose_name='Аватар')),
                ('background', models.ImageField(blank=True, upload_to='user-backgrounds/', verbose_name='Фон профиля')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
