# Generated by Django 3.2.13 on 2022-07-09 05:00

from django.db import migrations, models
import django_quill.fields
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user-avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='background',
            field=models.ImageField(blank=True, upload_to='user-backgrounds/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_newbie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_full_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=users.fields.LowercaseSlugField(default='', max_length=24, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=users.fields.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
