# Generated by Django 3.2.13 on 2022-06-02 03:24

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=users.fields.LowercaseSlugField(max_length=24, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
