# Generated by Django 3.2.13 on 2022-05-24 08:02

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=users.fields.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
