# Generated by Django 3.2.13 on 2022-05-24 08:25

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=users.fields.LowercaseCharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
