# Generated by Django 3.2.13 on 2022-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_newbie',
            field=models.BooleanField(default=True),
        ),
    ]
