# Generated by Django 3.2.13 on 2022-05-25 04:15

from django.db import migrations, models
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(default=users.fields.LowercaseCharField(max_length=24, unique=True), max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=users.fields.LowercaseCharField(max_length=24, unique=True),
        ),
    ]
