# Generated by Django 3.2.13 on 2022-05-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220525_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='display_username',
        ),
    ]
