# Generated by Django 3.2.13 on 2022-05-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_display_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
