# Generated by Django 3.2.13 on 2022-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_display_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
