# Generated by Django 3.2.13 on 2022-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_display_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_full_name',
            field=models.BooleanField(default=True),
        ),
    ]
