# Generated by Django 3.2.13 on 2022-05-25 12:42

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_show_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=cropperjs.models.CropperImageField(blank=True, upload_to='user-avatars/'),
        ),
    ]
