# Generated by Django 3.2.13 on 2022-05-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background',
            field=models.ImageField(blank=True, upload_to='user-backgrounds/'),
        ),
    ]
